name: Build and Deploy (Development)

on:
  push:
    branches: [development]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/vzma/web-api:${{ github.sha }}
            ghcr.io/vzma/web-api:development
            ghcr.io/vzma/web-api:latest
  deploy-docker-image:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Initialize doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log into K8s cluster
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-zma-website
      - name: Deploy image to cluster
        run: kubectl set image deployment/api api=ghcr.io/vzma/web-api:${{ github.sha }} --record -n zma-web-stack
      - name: Verify deployment
        run: kubectl rollout status deployment/api -n zma-web-stack
